import esbuild from 'esbuild';
import { gzipSync } from 'fflate';
import { builtinModules } from 'node:module';
import process from 'process';

import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync } from 'fs';

const builtins = [
  ...builtinModules,
  ...builtinModules.map((m) => `node:${m}`),
];

const pdfWorkerBytes = readFileSync(
  'node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs'
);
/** ~75 % plus petit qu’un embed texte brut → main.js sous la limite Sync 5 Mo. */
const pdfWorkerGzB64 = Buffer.from(
  gzipSync(pdfWorkerBytes, { level: 9 })
).toString('base64');



function copyPdfAssets() {

  mkdirSync('pdf-assets', { recursive: true });

  for (const dir of ['wasm', 'standard_fonts', 'iccs']) {

    cpSync(`node_modules/pdfjs-dist/${dir}`, `pdf-assets/${dir}`, {

      recursive: true,

    });

  }

}



function copyFoliateAssets() {
  if (!existsSync('node_modules/foliate-js')) return;
  cpSync('node_modules/foliate-js', 'foliate', { recursive: true });

  cpSync('src/assets/foliate/epub-bridge.html', 'foliate/epub-bridge.html');

  cpSync('src/assets/foliate/epub-bridge.js', 'foliate/epub-bridge.js');

}

/** Lecteur EPUB : un seul fichier à côté de main.js (téléchargeable depuis les réglages). */
async function buildFoliateViewBundle() {
  if (!existsSync('foliate/view.js')) return;
  await esbuild.build({
    entryPoints: ['foliate/view.js'],
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2020',
    outfile: 'foliate-view.mjs',
    minify: prod,
    logLevel: 'info',
  });
}

const banner = `/*

THIS IS A GENERATED/BUNDLED FILE BY ESBUILD

if you want to view the source, please visit the github repository of this plugin

*/

`;



const prod = process.argv[2] === 'production';

// foliate/epubcfi.js doit exister avant le bundle (import depuis src/readers/epub).
copyFoliateAssets();

esbuild

  .build({

    banner: {

      js: banner,

    },

    entryPoints: ['./src/main.ts'],

    bundle: true,

    external: [

      'obsidian',

      'electron',

      '@codemirror/autocomplete',

      '@codemirror/closebrackets',

      '@codemirror/collab',

      '@codemirror/commands',

      '@codemirror/comment',

      '@codemirror/fold',

      '@codemirror/gutter',

      '@codemirror/highlight',

      '@codemirror/history',

      '@codemirror/language',

      '@codemirror/lint',

      '@codemirror/matchbrackets',

      '@codemirror/panel',

      '@codemirror/rangeset',

      '@codemirror/rectangular-selection',

      '@codemirror/search',

      '@codemirror/state',

      '@codemirror/stream-parser',

      '@codemirror/text',

      '@codemirror/tooltip',

      '@codemirror/view',

      'node:*',

      ...builtins,

    ],

    format: 'cjs',

    watch: !prod,

    target: 'es2020',

    logLevel: 'info',

    sourcemap: prod ? false : 'inline',

    treeShaking: true,

    outfile: 'main.js',

    minify: prod,

    define: prod
      ? {
          __PDF_WORKER_GZ_B64__: JSON.stringify(pdfWorkerGzB64),
          __PDF_WORKER_CODE__: '""',
        }
      : {
          __PDF_WORKER_GZ_B64__: '""',
          __PDF_WORKER_CODE__: JSON.stringify(
            pdfWorkerBytes.toString('utf8')
          ),
        },

  })

  .then(() => {

    copyFileSync(

      'node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs',

      'pdf.worker.min.mjs'

    );

    copyPdfAssets();

    return buildFoliateViewBundle();

  })

  .catch((err) => {
    console.error('[PandoCit build]', err);
    process.exit(1);
  });

